[package]
name = "tcp_ip"
version = "0.1.0"
edition = "2021"

[dependencies]
bytes = "1.9"
crossbeam = "0.8.4"
dashmap = "6.1"
flume = { version = "0.11", features = ["async"] }
log = "0.4"
parking_lot = "0.12"
pnet_packet = "0.35"
rand = "0.8"
tokio = { version = "1.42", features = ["full"] }
tokio-util = "0.7.13"

[dev-dependencies]
anyhow = "1"
env_logger = "0.11"
packet = "0.1"
tun-rs = { version = "=1.4.9", features = ["async"] }

[[example]]
name = "tcp"

[[example]]
name = "udp"

[[example]]
name = "icmp"

[[example]]
name = "tcp-proxy"
